- name: Copy dotfiles to home directory
  copy:
    src: "./{{ item }}"
    dest: "/home/{{ owner }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0775
  with_items:
    - .config
    - .icons
    - .local
    - .mpd
    - .ncmpcpp
    - .scripts
    - .dmrc
    - .face
    - .fonts.conf
    - .gtkrc-2.0
    - .tmux.conf
    - .zshenv
  become_user: "{{ owner }}"
