- name: Upgrade packages
  command:
    cmd: "sudo pacman -Syu"

- name: Clear paru cache
  shell: "sudo rm -rf /home/{{ owner }}/.cache/paru/clone"

- name: Install packages
  shell: "paru -S --noconfirm --nocheck --skipreview --nodevel --norebuild --noredownload {{ item }}"
  with_items: "{{ dependencies }}"
  become: true

- name: Remove unused packages
  shell: "paru -R --noconfirm {{ item }} || echo 1"
  ignore_errors: true
  with_items: "{{ remove_dependencies }}"

- name: Fetch zap-zsh
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh
    return_content: true
  register: zap_installer

- name: Run zap-zsh installer
  ansible.builtin.shell:
    cmd: zsh -s
    stdin: "{{ zap_installer.content }}"

- name: Install themes
  include_tasks: themes.yml

- name: Install dotfiles
  include_tasks: dotfiles.yml
