---
- name: Set zsh as default shell
  ansible.builtin.shell:
    cmd: "sudo chsh -s $(which zsh)"

- name: Fetch zap-zsh
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh
    return_content: true
  register: zap_installer

- name: Run zap-zsh installer
  ansible.builtin.shell:
    cmd: zsh -s
    stdin: "{{ zap_installer.content }}"

- name: Install modprobe modules
  include_tasks: modprobe.yml

- name: Install themes
  include_tasks: themes.yml

- name: Install dotfiles
  include_tasks: dotfiles.yml
