- name: Add i915 enable_fbc module
  community.general.modprobe:
    name: i915
    state: present
    params: 'enable_fbc=1'

- name: Add i915 fastboot module
  community.general.modprobe:
    name: i915
    state: present
    params: 'fastboot=1'
