#!/bin/bash

dependencies=$(sed 's/.*/&/;$!s/$/ /' ./scripts/dependencies.txt | tr -d '\n')
remove_dependencies=$(sed 's/.*/&/;$!s/$/ /' ./scripts/remove_dependencies.txt | tr -d '\n')

sudo rm -rf $HOME/.cache/paru/clone

paru -S $dependencies
paru -R $remove_dependencies || echo "Warning: Remove packages not work"
