---
- name: Download and set grub theme
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Download asus-rog.tar
      get_url:
        url: "https://github.com/AdisonCavani/distro-grub-themes/raw/master/themes/asus-rog.tar"
        dest: "/tmp/asus-rog.tar"

    - name: Create /tmp/asus-rog directory
      file:
        path: "/tmp/asus-rog"
        state: directory

    - name: Extract asus-rog.tar
      unarchive:
        src: "/tmp/asus-rog.tar"
        dest: "/tmp/asus-rog"
        remote_src: true

    - name: Copy asus-rog files to grub themes directory
      synchronize:
        src: "/tmp/asus-rog/"
        dest: "/boot/grub/themes/asus-rog"
        delete: true

    - name: Set grub theme to asus-rog
      replace:
        path: /etc/default/grub
        regexp: "^GRUB_THEME=.*$"
        replace: "GRUB_THEME=/boot/grub/themes/asus-rog/theme.txt"
        backup: yes

    - name: Set grub gfxmode to 2560x1440
      replace:
        path: /etc/default/grub
        regexp: "^GRUB_GFXMODE=.*$"
        replace: "GRUB_GFXMODE=2560x1440"
        backup: yes

    - name: Check if splash is already present in GRUB_CMDLINE_LINUX_DEFAULT
      command: grep -i 'splash' /etc/default/grub
      register: splash_present
      changed_when: false
      failed_when: false

    - name: Update GRUB_CMDLINE_LINUX_DEFAULT
      replace:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT='(.*?)'"
        replace: "GRUB_CMDLINE_LINUX_DEFAULT='\\1 splash'"
        backup: yes
      when: not splash_present.stdout

    - name: Update grub
      command: update-grub
