---
- name: Clone sddm-themes repository and set SDDM theme
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Clone sddm-themes repository
      git:
        repo: https://github.com/catppuccin/sddm.git
        dest: "/tmp/sddm-themes"
        version: main

    - name: Copy sddm-themes to /usr/share/sddm/themes
      synchronize:
        src: "/tmp/sddm-themes/src/"
        dest: "/usr/share/sddm/themes"
        delete: true

    - name: Check if theme is already present in /etc/sddm.conf
      command: grep -i 'Current=' /etc/sddm.conf
      register: theme_present
      changed_when: false
      failed_when: false

    - name: Update SDDM theme in /etc/sddm.conf
      lineinfile:
        path: "/etc/sddm.conf"
        regexp: "^Current=.*"
        line: "Current=catppuccin-latte"
        backrefs: yes
        state: present
        create: yes
      when: theme_present.stdout

    - name: Update SDDM theme in /etc/sddm.conf
      lineinfile:
        path: "/etc/sddm.conf"
        insertafter: "^\\[Theme\\]"
        line: "Current=catppuccin-latte"
        state: present
        create: yes
      when: not theme_present.stdout

    - name: Delete sddm-themes folder
      file:
        path: "/tmp/sddm-themes"
        state: absent
