---
- name: Clone sddm-themes repository and set SDDM theme
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - sddm-git

    - name: Clone sddm-themes repository
      git:
        repo: https://github.com/catppuccin/sddm.git
        dest: "/tmp/sddm-themes"
        version: main

    - name: Copy sddm-themes to /usr/share/sddm/themes
      synchronize:
        src: "/tmp/sddm-themes/src/"
        dest: "/usr/share/sddm/themes"
        delete: true

    - name: Update SDDM theme in /usr/lib/sddm/sddm.conf.d/default.conf
      lineinfile:
        path: "/usr/lib/sddm/sddm.conf.d/default.conf"
        regexp: "^Current=.*"
        line: "Current=catppuccin-latte"
        backrefs: yes
        state: present
        create: yes

    - name: Delete sddm-themes folder
      file:
        path: "/tmp/sddm-themes"
        state: absent

    - name: Enable service sddm service
      ansible.builtin.service:
        name: sddm
        enabled: yes